apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.labels.microservice }}
  name: {{ .Values.labels.microservice }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.labels.microservice }}
    port: {{ .Values.service.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.service.containerPort }}
  selector:
    service: {{ .Values.labels.microservice }}
  type: {{ .Values.service.type }}