# Default values for app-2
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
labels:
  microservice: app-2

replicaCount: 1

image:
  repository: guydockerhub
  name: pythonapp
  tag: 16
  pullPolicy: IfNotPresent

targetUrl:
  url: "https://google.com"

file: "./microservices_app.py"


resources:
  requests:
    cpu: 200m
    memory: 1280Mi
  limits:
    cpu: 400m
    memory: 1536Mi

readiness:
  initialDelay: 1
  period: 1
  timeout: 1
liveness:
  initialDelay: 1
  period: 1
  timeout: 1

service:
  type: ClusterIP
  containerPort: 5000


