# Default values for app-1
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
labels:
  microservice: app-1

replicaCount: 1

image:
  repository: guydockerhub
  name: pythonapp
  tag: 24
  pullPolicy: IfNotPresent

targetUrl: false
file: "./numbers_api_app.py"


domain1: app-1.odd-application.com
domain2: app-1.even-application.com

resources:
  requests:
    cpu: 200m
    memory: 1280Mi
  limits:
    cpu: 400m
    memory: 1536Mi

readiness:
  initialDelay: 5
  period: 1
  timeout: 2
liveness:
  initialDelay: 5
  period: 1
  timeout: 2

service:
  type: NodePort
  containerPort: 5000


