name: Python App CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'Service name to deploy to Minikube'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status

      - name: Build Docker Image
        run: |
          docker build -t pythonapp:${{ github.run_number }} .
          docker tag pythonapp:${{ github.run_number }} ${DOCKER_USERNAME}/pythonapp:${{ github.run_number }}

      - name: Push Docker Image to Docker Hub
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker push ${DOCKER_USERNAME}/pythonapp:${{ github.run_number }}

      - name: Configure kubectl for Minikube
        run: |
          kubectl config use-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl apply -f ./minikubepythontask/helm/ helm/${{ inputs.service_name }}.yaml

      - name: Wait for Deployment to be Ready
        run: |
          kubectl rollout status deployment/${{ inputs.service_name }}

